name: mealbudget_frontend
description: Simple Flutter web app for the MealBudget case study.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # HTTP client for backend calls
  dio: ^5.4.0

  # Routing
  go_router: ^14.2.0

  # State management (simple, φοιτητικό)
  flutter_riverpod: ^2.5.1

  # Charts for results page
  fl_chart: ^1.1.1

  # Utility libs (προαιρετικά, αλλά βοηθάνε)
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/